### ISSUE TITLE
ROS fails to launch scout mini

### ISSUE THREAD

**Issue by jmalswarm** [agilexrobotics/scout_ros#1]
roslaunch scout_bringup scout_mini_robot_base.launch
... logging to /home/harvey/.ros/log/1fce64a8-13f9-11ec-8fb5-ec2e98ca62cd/roslaunch-harvey-desktop-18794.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://harvey-desktop:44193/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /scout_base_node/base_frame: base_link
 * /scout_base_node/is_scout_mini: True
 * /scout_base_node/odom_frame: odom
 * /scout_base_node/odom_topic_name: odom
 * /scout_base_node/port_name: can0
 * /scout_base_node/simulated_robot: False

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    scout_base_node (scout_base/scout_base_node)

auto-starting new master
process[master]: started with pid [18813]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1fce64a8-13f9-11ec-8fb5-ec2e98ca62cd
process[rosout-1]: started with pid [18829]
started core service [/rosout]
process[scout_base_node-2]: started with pid [18840]
process[joint_state_publisher-3]: started with pid [18847]
process[robot_state_publisher-4]: started with pid [18854]
Working as scout mini: 1
Start listening to port: can0
Detected protocol: UNKONWN
================================================================================REQUIRED process [scout_base_node-2] has died!
process has died [pid 18840, exit code 255, cmd /home/harvey/Desktop/GitHub/project_heatmap/swarmbot/GUI_demo/robotics/warthog_ws/devel/lib/scout_base/scout_base_node __name:=scout_base_node __log:=/home/harvey/.ros/log/1fce64a8-13f9-11ec-8fb5-ec2e98ca62cd/scout_base_node-2.log].
log file: /home/harvey/.ros/log/1fce64a8-13f9-11ec-8fb5-ec2e98ca62cd/scout_base_node-2*.log
Initiating shutdown!
================================================================================
[robot_state_publisher-4] killing on exit
[joint_state_publisher-3] killing on exit
[scout_base_node-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by jmalswarm** [comment]
<launch>

    <arg name="port_name" value="can0" />
    <arg name="simulated_robot" value="false" />
    <arg name="model_xacro" default="$(find scout_description)/urdf/scout_v2.xacro" />
    <arg name="odom_topic_name" default="odom" />
    <arg name="is_scout_mini" default="true" />

    <include file="$(find scout_base)/launch/scout_base.launch">
        <arg name="port_name" default="$(arg port_name)" />
        <arg name="simulated_robot" default="$(arg simulated_robot)" />
        <arg name="odom_topic_name" default="$(arg odom_topic_name)" />
        <arg name="is_scout_mini" default="$(arg is_scout_mini)" />
    </include>

    <include file="$(find scout_description)/launch/description.launch">
        <arg name="model_xacro" default="$(arg model_xacro)" />
    </include>

</launch>

**Comment by jmalswarm** [comment]
why is this happening?

**Comment by cristinaluna** [comment]
I have the same problem using the Scout 2.0 scout_base node

**Comment by cristinaluna** [comment]
Solved, it happens when the can communication is not working. Maybe it's better to use can2can instead of can2usb

**Comment by diegotiozzo21** [comment]
I have this problem too. I connected the edu kit from a scout mini in a scout 2.0, with the plug in front of the robot. 
I can see incoming data: using "candump can0". However, when i run "scout_robot_base.launch", the node crashes after "Detected protocol: UNKOWN".

**Comment by diegotiozzo21** [comment]
Solved!
It was because the can plug in front of the robot is not for users. To connect the edu kit in a scout 2.0, the plug on top or on the tail of the robot must be used.
