### ISSUE TITLE
关于webots仿真：webots仿真支持已经弃用了吗

### ISSUE THREAD

**Issue by hanyan009** [agilexrobotics/scout_ros#20]
在b站视频BV1wp4y1q7yP里看到了能够进行webots仿真，但是这里却没找到对应的launch文件

**Comment by lagrangeluo** [comment]
> 在b站视频BV1wp4y1q7yP里看到了能够进行webots仿真，但是这里却没找到对应的launch文件

是的webots目前已经不支持了
