### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gongyue666** [agilexrobotics/scout_ros#5]
/home/gy2/3rd/drivers_ws/src/ugv_sdk/include/ugv_sdk/details/async_port/async_can.hpp:41:16: error: ‘basic_stream_descriptor’ in namespace ‘asio::posix’ does not name a template type; did you mean ‘stream_descriptor’?
   41 |   asio::posix::basic_stream_descriptor<> socketcan_stream_;
      |                ^~~~~~~~~~~~~~~~~~~~~~~
      |                stream_descriptor
/home/gy2/3rd/drivers_ws/src/ugv_sdk/include/ugv_sdk/details/async_port/async_can.hpp:49:34: error: ‘asio::posix::basic_stream_descriptor’ has not been declared
   49 |                     asio::posix::basic_stream_descriptor<> &stream);
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~
/home/gy2/3rd/drivers_ws/src/ugv_sdk/include/ugv_sdk/details/async_port/async_can.hpp:49:57: error: expected ‘,’ or ‘...’ before ‘<’ token
   49 |                     asio::posix::basic_stream_descriptor<> &stream);

**Comment by asimonov** [comment]
adding this to scout_base/CMakeLists.txt

```
target_compile_definitions(scout_base_node PUBLIC ASIO_ENABLE_OLD_SERVICES)
```

solved it for me
